ad-matrix.o: ad-matrix.c ../local/include/xtend/dsv.h \
  ../local/include/biolibc/vcf.h ../local/include/biolibc/sam.h \
  ../local/include/biolibc/biolibc.h \
  ../local/include/biolibc/biostring.h ad-matrix.h
	${CC} -c ${CFLAGS} ad-matrix.c

